// <auto-generated />
using System;
using Infrastructure.Db.App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Db.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423144445_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Db.App.Entities.LlmUsageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens")
                        .HasComment("Число токенов на выходе");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost")
                        .HasComment("Стоимость запроса (если провайдер вернул)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms")
                        .HasComment("Длительность HTTP-запроса, мс");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message")
                        .HasComment("Сообщение об ошибке при неуспехе");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_json")
                        .HasComment("Входящий запрос к LLM в формате JSON");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success")
                        .HasComment("Успешное завершение попытки (HTTP и разбор ответа)");

                    b.Property<string>("LlmModel")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("llm_model")
                        .HasComment("Имя модели LLM");

                    b.Property<string>("LlmRequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("llm_request_id")
                        .HasComment("Идентификатор запроса/ответа у провайдера LLM");

                    b.Property<string>("LlmResponse")
                        .HasColumnType("text")
                        .HasColumnName("llm_response")
                        .HasComment("Текст ответа ассистента или сырое тело ответа при сбое разбора");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens")
                        .HasComment("Число токенов на входе");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.HasKey("Id")
                        .HasName("pk_llm_usages");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_llm_usages_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_llm_usages_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_llm_usages_updated_by_id");

                    b.ToTable("llm_usages", "stat");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.LogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<string>("Log")
                        .HasColumnType("jsonb")
                        .HasColumnName("log")
                        .HasComment("Структурированные данные лога в формате JSON");

                    b.Property<string>("LogMessage")
                        .HasColumnType("text")
                        .HasColumnName("log_message")
                        .HasComment("Текстовое сообщение лога");

                    b.Property<int?>("LogSource")
                        .HasColumnType("integer")
                        .HasColumnName("log_source")
                        .HasComment("Источник лога: бэкенд или фронтенд");

                    b.Property<string>("LogType")
                        .HasColumnType("text")
                        .HasColumnName("log_type")
                        .HasComment("Тип/категория лога");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор пользователя (если известен)");

                    b.HasKey("Id")
                        .HasName("pk_logs");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_logs_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_logs_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_logs_updated_by_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_logs_user_id");

                    b.ToTable("logs");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.StatEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<string>("Data")
                        .HasColumnType("text")
                        .HasColumnName("data")
                        .HasComment("Данные о событии");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds")
                        .HasComment("Длительность выполняемого события");

                    b.Property<long?>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id")
                        .HasComment("Идентификатор сессии");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type")
                        .HasComment("Тип события");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор пользователя");

                    b.HasKey("Id")
                        .HasName("pk_stat_events");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_stat_events_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_stat_events_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_stat_events_updated_by_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_stat_events_user_id");

                    b.ToTable("stat_events", "stat");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("ConfirmedPolicyAndDocuments")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed_policy_and_documents")
                        .HasComment("Пользователь подтвердил ознакомление с политикой и документами.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.LlmUsageEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_llm_usages_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_llm_usages_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_llm_usages_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.LogEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_logs_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_logs_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_logs_users_updated_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_logs_users_user_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.StatEventEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_stat_events_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_stat_events_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_stat_events_users_updated_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stat_events_users_user_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
