// <auto-generated />
using System;
using Infrastructure.Db.App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Db.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424145821_AddKnowledgeBaseSchema")]
    partial class AddKnowledgeBaseSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Db.App.Entities.ChatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at")
                        .HasComment("Время последнего сообщения в чате");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status")
                        .HasComment("Агрегированный статус чата");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title")
                        .HasComment("Краткий заголовок чата");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор пользователя");

                    b.HasKey("Id")
                        .HasName("pk_chats");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_chats_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_chats_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_chats_updated_by_id");

                    b.HasIndex("UserId", "UpdatedAt")
                        .IsDescending(false, true);

                    b.ToTable("chats", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.KnowledgeCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("Название категории базы знаний");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_categories");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_knowledge_categories_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_knowledge_categories_deleted_by_id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_knowledge_categories_updated_by_id");

                    b.ToTable("knowledge_categories", "knowledge");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.KnowledgeTitleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content")
                        .HasComment("HTML-контент статьи");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<string>("Excerpt")
                        .HasColumnType("text")
                        .HasColumnName("excerpt")
                        .HasComment("Краткое описание статьи");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("images")
                        .HasComment("Список изображений статьи");

                    b.Property<Guid>("KnowledgeCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_category_id")
                        .HasComment("Идентификатор категории");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title")
                        .HasComment("Заголовок статьи");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_titles");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_knowledge_titles_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_knowledge_titles_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_knowledge_titles_updated_by_id");

                    b.HasIndex("KnowledgeCategoryId", "Title");

                    b.ToTable("knowledge_titles", "knowledge");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.LlmUsageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens")
                        .HasComment("Число токенов на выходе");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost")
                        .HasComment("Стоимость запроса (если провайдер вернул)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms")
                        .HasComment("Длительность HTTP-запроса, мс");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message")
                        .HasComment("Сообщение об ошибке при неуспехе");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_json")
                        .HasComment("Входящий запрос к LLM в формате JSON");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success")
                        .HasComment("Успешное завершение попытки (HTTP и разбор ответа)");

                    b.Property<string>("LlmModel")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("llm_model")
                        .HasComment("Имя модели LLM");

                    b.Property<string>("LlmRequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("llm_request_id")
                        .HasComment("Идентификатор запроса/ответа у провайдера LLM");

                    b.Property<string>("LlmResponse")
                        .HasColumnType("text")
                        .HasColumnName("llm_response")
                        .HasComment("Текст ответа ассистента или сырое тело ответа при сбое разбора");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens")
                        .HasComment("Число токенов на входе");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.HasKey("Id")
                        .HasName("pk_llm_usages");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_llm_usages_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_llm_usages_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_llm_usages_updated_by_id");

                    b.ToTable("llm_usages", "stat");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.LogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<string>("Log")
                        .HasColumnType("jsonb")
                        .HasColumnName("log")
                        .HasComment("Структурированные данные лога в формате JSON");

                    b.Property<string>("LogMessage")
                        .HasColumnType("text")
                        .HasColumnName("log_message")
                        .HasComment("Текстовое сообщение лога");

                    b.Property<int?>("LogSource")
                        .HasColumnType("integer")
                        .HasColumnName("log_source")
                        .HasComment("Источник лога: бэкенд или фронтенд");

                    b.Property<string>("LogType")
                        .HasColumnType("text")
                        .HasColumnName("log_type")
                        .HasComment("Тип/категория лога");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор пользователя (если известен)");

                    b.HasKey("Id")
                        .HasName("pk_logs");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_logs_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_logs_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_logs_updated_by_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_logs_user_id");

                    b.ToTable("logs");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.MessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_id")
                        .HasComment("Идентификатор чата");

                    b.Property<string>("ClientRequestId")
                        .HasColumnType("text")
                        .HasColumnName("client_request_id")
                        .HasComment("Ключ идемпотентности клиентского запроса");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<string>("FailureCode")
                        .HasColumnType("text")
                        .HasColumnName("failure_code")
                        .HasComment("Код ошибки обработки");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason")
                        .HasComment("Причина ошибки обработки");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count")
                        .HasComment("Число попыток обработки");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role")
                        .HasComment("Роль отправителя");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status")
                        .HasComment("Статус обработки сообщения");

                    b.Property<string>("TextHtml")
                        .HasColumnType("text")
                        .HasColumnName("text_html")
                        .HasComment("Санитизированный HTML пользователя или ассистента");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ClientRequestId")
                        .IsUnique()
                        .HasFilter("\"client_request_id\" IS NOT NULL");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_messages_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_messages_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_messages_updated_by_id");

                    b.HasIndex("ChatId", "CreatedAt");

                    b.ToTable("messages", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.MessageImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height")
                        .HasComment("Высота изображения");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id")
                        .HasComment("Идентификатор сообщения");

                    b.Property<string>("MimeType")
                        .HasColumnType("text")
                        .HasColumnName("mime_type")
                        .HasComment("MIME-тип изображения");

                    b.Property<string>("PlantIdNormalizedJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("plant_id_normalized_json")
                        .HasComment("Нормализованный ответ PlantId");

                    b.Property<string>("PlantIdRawJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("plant_id_raw_json")
                        .HasComment("Сырой ответ PlantId");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes")
                        .HasComment("Размер изображения в байтах");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasComment("Порядок изображения в сообщении");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_url")
                        .HasComment("URL изображения в хранилище");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width")
                        .HasComment("Ширина изображения");

                    b.HasKey("Id")
                        .HasName("pk_message_images");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_message_images_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_message_images_deleted_by_id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_message_images_message_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_message_images_updated_by_id");

                    b.ToTable("message_images", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.ProcessingJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt")
                        .HasComment("Номер попытки");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_id")
                        .HasComment("Идентификатор чата");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error")
                        .HasComment("Последняя ошибка обработки");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until")
                        .HasComment("Время удержания lock на задаче");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts")
                        .HasComment("Максимальное число попыток");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id")
                        .HasComment("Идентификатор сообщения");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status")
                        .HasComment("Статус задачи");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.HasKey("Id")
                        .HasName("pk_processing_jobs");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("ix_processing_jobs_chat_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_processing_jobs_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_processing_jobs_deleted_by_id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_processing_jobs_message_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_processing_jobs_updated_by_id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("processing_jobs", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.StatEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("ИД сущности.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Когда сущность была создана.");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Кто создал сущность.");

                    b.Property<string>("Data")
                        .HasColumnType("text")
                        .HasColumnName("data")
                        .HasComment("Данные о событии");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("Когда сущность была удалена.");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id")
                        .HasComment("Кто удалил сущность.");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds")
                        .HasComment("Длительность выполняемого события");

                    b.Property<long?>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id")
                        .HasComment("Идентификатор сессии");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type")
                        .HasComment("Тип события");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("Когда сущность была в последний раз обновлена.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Кто обновил сущность.");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор пользователя");

                    b.HasKey("Id")
                        .HasName("pk_stat_events");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_stat_events_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_stat_events_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_stat_events_updated_by_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_stat_events_user_id");

                    b.ToTable("stat_events", "stat");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "app");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.ChatEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_chats_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_chats_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_chats_users_updated_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chats_users_user_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.KnowledgeCategoryEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_knowledge_categories_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_knowledge_categories_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_knowledge_categories_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.KnowledgeTitleEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_knowledge_titles_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_knowledge_titles_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.KnowledgeCategoryEntity", "Category")
                        .WithMany("Titles")
                        .HasForeignKey("KnowledgeCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_titles_knowledge_categories_category_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_knowledge_titles_users_updated_by_id");

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.LlmUsageEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_llm_usages_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_llm_usages_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_llm_usages_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.LogEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_logs_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_logs_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_logs_users_updated_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_logs_users_user_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.MessageEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.ChatEntity", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_chats_chat_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_messages_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_messages_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_messages_users_updated_by_id");

                    b.Navigation("Chat");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.MessageImageEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_message_images_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_message_images_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.MessageEntity", "Message")
                        .WithMany("Images")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_images_messages_message_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_message_images_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Message");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.ProcessingJobEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.ChatEntity", "Chat")
                        .WithMany("ProcessingJobs")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_processing_jobs_chats_chat_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_processing_jobs_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_processing_jobs_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.MessageEntity", "Message")
                        .WithMany("ProcessingJobs")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_processing_jobs_messages_message_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_processing_jobs_users_updated_by_id");

                    b.Navigation("Chat");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Message");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.StatEventEntity", b =>
                {
                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_stat_events_users_created_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .HasConstraintName("fk_stat_events_users_deleted_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .HasConstraintName("fk_stat_events_users_updated_by_id");

                    b.HasOne("Infrastructure.Db.App.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stat_events_users_user_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.ChatEntity", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("ProcessingJobs");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.KnowledgeCategoryEntity", b =>
                {
                    b.Navigation("Titles");
                });

            modelBuilder.Entity("Infrastructure.Db.App.Entities.MessageEntity", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ProcessingJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
